ALTER TABLE "categories" ADD COLUMN "slug" text;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_user_id_slug_key" UNIQUE("user_id","slug");--> statement-breakpoint
-- Hand-written backfill (not generated by drizzle-kit): stamp the slug onto rows that
-- came from the original 14-item seed, so existing users' categories start translating
-- and restore-defaults recognizes them even if they later rename one.
-- Matched on the full fingerprint (name + icon + type) rather than name alone: a category
-- the user hand-made and happened to call "Groceries" almost certainly carries a different
-- (or NULL) icon, so it keeps its prose name instead of being silently relabelled.
UPDATE "categories" AS c SET "slug" = m.slug
FROM (VALUES
  ('Salary'::text,        'i-lucide-briefcase'::text,     'INCOME'::text,  'salary'::text),
  ('Freelance',           'i-lucide-laptop',              'INCOME',        'freelance'),
  ('Gifts',               'i-lucide-gift',                'INCOME',        'gifts'),
  ('Other Income',        'i-lucide-plus-circle',         'INCOME',        'otherIncome'),
  ('Groceries',           'i-lucide-shopping-cart',       'EXPENSE',       'groceries'),
  ('Dining',              'i-lucide-utensils',            'EXPENSE',       'dining'),
  ('Transport',           'i-lucide-car',                 'EXPENSE',       'transport'),
  ('Housing',             'i-lucide-house',               'EXPENSE',       'housing'),
  ('Utilities',           'i-lucide-zap',                 'EXPENSE',       'utilities'),
  ('Health',              'i-lucide-heart-pulse',         'EXPENSE',       'health'),
  ('Shopping',            'i-lucide-shopping-bag',        'EXPENSE',       'shopping'),
  ('Entertainment',       'i-lucide-gamepad-2',           'EXPENSE',       'entertainment'),
  ('Fees',                'i-lucide-receipt',             'EXPENSE',       'fees'),
  ('Other',               'i-lucide-ellipsis',            'EXPENSE',       'other')
) AS m(name, icon, type, slug)
WHERE c."slug" IS NULL
  AND c."name" = m.name
  AND c."icon" = m.icon
  AND c."type" = m.type::"public"."transaction_type";